poanetwork/bridge-ui

README.md
Problem:
what is bridge-ui
what a user could do with bridge-ui
Solutions:
add info
=> README.md is missing the general description of the product. 

src/abis/ForeignBridge.json, src/components/RelayEvents.js, src/components/events/CollectedSignatures.js, src/components/events/SignedForDeposit.js, src/stores/ForeignStore.js
Problem: 
CollectedSignatures and SignedForWithdrawal events don't show up when a user is trying to locate all Withdrawal events
Solution: 
Solution explained in #5
=> Show  CollectedSignatures and SignedForWithdrawal on Search. Part of #5

README.md
Problem:
After following the steps on the preparation for using the UI app I found that some instructions were not very clear.
Solution:
Improved some of the instructions to make them easier to understand.
=> (Improvement) readme instructions

src/stores/ForeignStore.js, src/stores/HomeStore.js, src/stores/TxStore.js
This is the last item of #20 
Sends a sweetalert when the token is received on another chain.
@rstormsf Please check on the displayed message of the alert, I can changed if needed.
=> add alert on tokens received

README.md
New playbooks for RPC version of bridge
=> Update Link to Ansible Playbooks

src/components/Loading.js, src/components/ProgressRing.js, src/stores/AlertStore.js, src/stores/ForeignStore.js, src/stores/TxStore.js
=> Wait 8 blocks on foreign network

src/stores/ForeignStore.js, src/stores/TxStore.js
=> Fix critical bug

src/stores/Web3Store.js
=> Fix Wrong error message metamask

src/components/Configuration.js, src/components/NetworkDetails.js, src/components/TransferAlert.js, src/stores/ForeignStore.js, src/stores/HomeStore.js
This includes:
- Show correct txHash. Closes #98 
- Renamed Max Total Balance
- Commas on Transfer confirmation numbers
- Network name on sweetAlert
=> Show correct txHash

src/stores/AlertStore.js, src/stores/ForeignStore.js, src/stores/HomeStore.js
Show a sweetalert only the first time there is a connection error on Home/Foreign network 
Closes #103
=> Fix Multiple Alerts on Connection Error

src/components/Bridge.js, src/stores/HomeStore.js, src/stores/Web3Store.js
Add the Loading overlay when changing account on Metamask to improve user experience while balances are loaded for the new account
=> Add Loading on Account Change

src/components/Bridge.js
Fix for issue $46
I did not test this since this is just a minor string change.
=> (Fix for issue #43) Fixes minor typo in error message text

src/components/Footer.js
Issue: #121 
Changed footer link for github to POA-Bridge repo as requested by @igorbarinov
=> feat(footer): Changed repo link to POA Bridge

e2e-script/docker-compose.yml, e2e-script/parity/Dockerfile, e2e-script/parity/Dockerfile-foreign, src/components/Bridge.js, src/components/Loading.js, src/components/ProgressRing.js, src/stores/TxStore.js, src/stores/utils/web3.js
- Add support for new Metamask window.ethereum global variable
- Ignore internal error triggered by web3 (only on new metamask build) that affected the UI.
- Minor fix on Loading screen, after `waiting for block confirmation` message dissapear, also numbers of block confirmation (`8/8`) are removed too  
Closes #139
=> Support Metamask changes

src/stores/Web3Store.js
=> Prevent displaying 0x0 address' balance when there's no wallet available

src/components/Bridge.js, src/components/Loading.js, src/components/ProgressRing.js, src/stores/TxStore.js, src/stores/utils/web3.js
=> Merge the develop-1.x branch to the master-1.x branch

README.md
README update: change Sokol faucet link to alias https://faucet.poa.network
=> Change Sokol faucet link to alias

public/index.html, src/components/Disclaimer.js, src/components/Footer.js
Changed the text and links for some components:
- Change from POA Bridge to TokenBridge
- Changed the Zendesk links to the Forum links
- Removed the support button
=> feat(text): Updated the text and links for some components

src/components/SocialIcons.js
Closes #198 
Changed <Link> to <a> on social icons, it should work fine now.
=> (fix) Broken links on footer.

.env.example, README.md
Recently two new parameters were introduced:
- `APP_STYLES` allows to specify a theme prepared for particular deployment (https://github.com/poanetwork/bridge-ui/pull/192)
- `REACT_APP_TITLE` allows to specify the page title (https://github.com/poanetwork/bridge-ui/pull/201)
=> README update due to recent improvements

e2e-script/parity/Dockerfile, e2e-script/parity/Dockerfile-foreign, src/components/Bridge.js, src/components/NetworkDetails.js, src/components/__tests__/NetworkDetails.test.js, src/stores/ForeignStore.js, src/stores/utils/__tests__/contract.test.js, src/stores/utils/bridgeMode.js, src/stores/utils/contract.js
=> Add support erc677 on Foreign network for erc-to-erc mode

e2e-script/MetaMask.js, e2e-script/config.json, e2e-script/docker-compose.yml, e2e-script/run-tests.sh, e2e-script/scripts/blocks.js
Closes #216 
@rzadp Please check if e2e tests are working now for you
=> Update e2e tests urls

README.md, src/components/NoWallet.js
No longer need the download page as the website fits it better now :)
=> update AlphaWallet links to point to website
